// import SKILLS_CATEGORY from '~/environment'
import mongoose from 'mongoose'
import { REVIEW_GOALS, GOAL_STATUS } from '~/environment'

const Schema = mongoose.Schema

const ObjectId = Schema.Types.ObjectId

export const goalSchema = new Schema({
  goalName: {
    type: String,
    required: true
  },
  goalType: {
    type: String,
    enum: REVIEW_GOALS,
    required: true
  },
  setBy: ObjectId,
  reviewId: ObjectId,
  organizationId: ObjectId,
  teamId: ObjectId,
  user: ObjectId,
  measures: [
    {
      measureName: {
        type: String,
        required: true
      },
      completed: {
        type: Boolean,
        default: false
      },
      successRate: Number
    }
  ],
  relatedSkills: [ObjectId],
  skills: [
    {
      skillId: ObjectId,
      level: Number,
      related: Boolean
    }
  ],
  feedback: String,
  createdAt: {
    type: Date,
    required: true,
    default: Date.now
  },
  updatedAt: {
    type: Date,
    required: true,
    default: Date.now
  },
  status: {
    type: String,
    enum: GOAL_STATUS,
    default: 'DRAFT'
  },
  reviewedAt: Date,
  autogenerated: {
    type: Boolean,
    default: false
  },
  isPrivate: {
    type: Boolean,
    default: false
  },
  deadline: Date,
  fromTemplate: ObjectId,
  seen: Boolean
})

const Goal = mongoose.model('Goal', goalSchema)
export default Goal
