export { hashString } from './hash'
export { removeTokens } from './_removeTokens'
export { isNotInnentialEmail } from './_checkInnentialEmail'
export { default as RouteManager } from './_routeManager'
export { removeDuplicates } from './_array'
export { default as GetNewContent } from './GetNewContent'
export { default as ShareFromEmail } from './ShareFromEmail'
export { default as GetPaidContent } from './GetPaidContent'
export { default as LikeContentFromEmail } from './LikeContentFromEmail'
export { default as DislikeContentFromEmail } from './DislikeContentFromEmail'
export { default as ResetLearningPreferences } from './ResetFilters'
export { default as GenerateCalendarEvents } from './GenerateCalendarEvents'
export { default as useTracker } from './useTracker'
export { default as initializeHotjarTracker } from './initializeHotjarTracker'
export { default as initializeSegment } from './initializeSegment'
export { default as UserContext } from './_context'
export { emailCharacterValidator } from './_validators'
export { default as getInitials } from './_getInitials'
export {
  generateSpecialAvatar,
  default as generateInitialsAvatar
} from './_generateInitialsAvatar'
export { default as generatePseudoRandomColor } from './_randomColor'
export { default as monkeyPatchGoogleTranslate } from './_monkeyPatchTranslate'
export { dateCombiner } from './_dateManager'
