export default [
  {
    source: 'Codeworks',
    bootcamp: 'Software Engineering Immersive',
    locations: 'Berlin',
    remote: true,
    startsAt: '2021-01-11',
    duration: 12,
    format: 'full-time',
    cost: 9800,
    financing: 'Pay when you get a job, Quotanda',
    url: 'https://codeworks.me/berlin/software-engineering-immersive-course/',
    score: 5,
    reviews: 60,
    languages: 'en',
    commission: 0.1,
    type: 'webdev',
    requiredCodingExperience: true
  },
  {
    source: 'Codeworks',
    bootcamp: 'Web Development Immersive',
    locations: 'Berlin',
    remote: true,
    startsAt: '2021-01-11',
    duration: 8,
    format: 'full-time',
    cost: 7800,
    financing: 'Quotanda',
    url: 'https://codeworks.me/berlin/web-development-immersive-course/',
    score: 5,
    reviews: 58,
    languages: 'en',
    commission: 0.1,
    type: 'webdev',
    requiredCodingExperience: false
  },
  {
    source: 'Ironhack',
    bootcamp: 'UX/UI Design',
    locations: 'Berlin',
    remote: true,
    startsAt: '2021-01-11',
    duration: '9, 24',
    format: 'full-time, part-time',
    cost: 7500,
    financing: 'Quotanda, Income share, Bildungsgutschein',
    url: 'https://www.ironhack.com/de/ux-ui-design/berlin',
    score: 4.88,
    reviews: 928,
    languages: 'en',
    commission: 0.1,
    type: 'uxui',
    requiredCodingExperience: false
  },
  {
    source: 'Ironhack',
    bootcamp: 'Data Analytics',
    locations: 'Berlin',
    remote: true,
    startsAt: '2021-01-11',
    duration: '9, 24',
    format: 'full-time, part-time',
    cost: 7500,
    financing: 'Quotanda, Income share, Bildungsgutschein',
    url: 'https://www.ironhack.com/de/data-analytics',
    score: 4.9,
    reviews: 954,
    languages: 'en',
    commission: 0.1,
    type: 'dataanalyst',
    requiredCodingExperience: false
  },
  {
    source: 'Ironhack',
    bootcamp: 'Web Development',
    locations: 'Berlin',
    remote: true,
    startsAt: '2021-01-11',
    duration: '9, 24',
    format: 'full-time, part-time',
    cost: 7500,
    financing: 'Quotanda, Income share, Bildungsgutschein',
    url: 'https://www.ironhack.com/de/webentwicklung',
    score: 4.87,
    reviews: 934,
    languages: 'en',
    commission: 0.1,
    type: 'webdev',
    requiredCodingExperience: false
  },
  // {
  //   source: 'Code Academy Berlin',
  //   bootcamp: 'Web Developer',
  //   locations: 'Berlin',
  //   remote: false,
  //   startsAt: '2020-11-23',
  //   duration: 12,
  //   format: 'full-time',
  //   cost: 6750,
  //   financing: 'Bildungsgutschein',
  //   url: 'https://www.codeacademyberlin.com/en/courses/web-development/',
  //   score: null,
  //   reviews: null,
  //   languages: 'en',
  //   commission: 0.065,
  //   type: 'webdev',
  //   requiredCodingExperience: false
  // },
  // {
  //   source: 'Code Academy Berlin',
  //   bootcamp: 'Data Science',
  //   locations: 'Berlin',
  //   remote: false,
  //   startsAt: '2020-11-23',
  //   duration: 16,
  //   format: 'full-time',
  //   cost: 6750,
  //   financing: 'Bildungsgutschein',
  //   url: 'https://www.codeacademyberlin.com/en/courses/data-science/',
  //   score: null,
  //   reviews: null,
  //   languages: 'en',
  //   commission: 0.065,
  //   type: 'datascience',
  //   requiredCodingExperience: false
  // },
  // {
  //   source: 'Code Academy Berlin',
  //   bootcamp: 'Data Analyst',
  //   locations: 'Berlin',
  //   remote: false,
  //   startsAt: '2020-11-23',
  //   duration: 12,
  //   format: 'full-time',
  //   cost: 6750,
  //   financing: 'Bildungsgutschein',
  //   url: 'https://www.codeacademyberlin.com/en/courses/data-science/',
  //   score: null,
  //   reviews: null,
  //   languages: 'en',
  //   commission: 0.065,
  //   type: 'dataanalyst',
  //   requiredCodingExperience: false
  // },
  {
    source: 'Wild Code School',
    bootcamp: 'Web Development',
    locations: 'Berlin',
    remote: true,
    startsAt: '2021-07-30',
    duration: 20,
    format: 'full-time',
    cost: 7020,
    financing: 'Bildungsgutschein, Income share, Discount',
    url:
      'https://www.wildcodeschool.com/en-GB/trainings/web-developer-full-time?campus=berlin',
    score: 4.82,
    reviews: 57,
    languages: 'en',
    commission: 0.06,
    type: 'webdev',
    requiredCodingExperience: false
  },
  {
    source: 'Wild Code School',
    bootcamp: 'Web Development',
    locations: 'Remote',
    remote: true,
    startsAt: '2021-07-30',
    duration: 20,
    format: 'full-time',
    cost: 7020,
    financing: 'Knoma, Lendwise, Discount, Scholarships',
    url:
      'https://www.wildcodeschool.com/en-GB/trainings/web-developer-full-time',
    score: 4.93,
    reviews: 56,
    languages: 'en',
    commission: 0.06,
    type: 'webdev',
    requiredCodingExperience: false
  },
  {
    source: 'Wild Code School',
    bootcamp: 'Data Analysis',
    locations: 'Remote',
    remote: true,
    startsAt: '2021-07-30',
    duration: 20,
    format: 'full-time',
    cost: 7020,
    financing: 'Knoma, Lendwise, Discount, Scholarships',
    url:
      'https://www.wildcodeschool.com/en-GB/trainings/data-analyst?campus=remote-english',
    score: 4.94,
    reviews: 64,
    languages: 'en',
    commission: 0.06,
    type: 'dataanalyst',
    requiredCodingExperience: false
  }
]
